// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: termostat_V1

#include "../ui.h"

void ui_comp_Dropdown_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Roller_create_hook(lv_obj_t * comp)
{
}
