// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: termostat_V1

#ifndef _TERMOSTAT_V1_UI_H
#define _TERMOSTAT_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../.pio/libdeps/esp32-4827S043C/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Fash_Animation(lv_obj_t * TargetObject, int delay);
void Wave1_Animation(lv_obj_t * TargetObject, int delay);
void Wave2_Animation(lv_obj_t * TargetObject, int delay);
void Off_Animation(lv_obj_t * TargetObject, int delay);
void On_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_BG1;
extern lv_obj_t * ui_lblCESIOUS;
void ui_event_Slider_Speed(lv_event_t * e);
extern lv_obj_t * ui_Slider_Speed;
extern lv_obj_t * ui_Slider_Battery;
extern lv_obj_t * ui_Group_Battery_Percent;
extern lv_obj_t * ui_Label_Number1;
extern lv_obj_t * ui_Label_Number2;
extern lv_obj_t * ui_Label_Number3;
extern lv_obj_t * ui_Label_Number4;
extern lv_obj_t * ui_Label_Number5;
extern lv_obj_t * ui_Group_Header2;
extern lv_obj_t * ui_Head_Group1;
extern lv_obj_t * ui_Group_Footer;
extern lv_obj_t * ui_Button_Group;
extern lv_obj_t * ui_BTN_Driving;
void ui_event_BTN_BG1(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_BTN_Battery;
void ui_event_BTN_BG2(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG2;
extern lv_obj_t * ui_ICN_Battery;
extern lv_obj_t * ui_BTN_MAp;
void ui_event_BTN_BG3(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG3;
extern lv_obj_t * ui_ICN_Map;
extern lv_obj_t * ui_Group_Battery;
extern lv_obj_t * ui_Group_Title1;
extern lv_obj_t * ui_Title_BG1;
extern lv_obj_t * ui_Label_Battery_Information;
extern lv_obj_t * ui_Group_Content1;
extern lv_obj_t * ui_Group_Charging;
extern lv_obj_t * ui_LabeL_Charging;
extern lv_obj_t * ui_Label_Charging_Number;
extern lv_obj_t * ui_Label_Percent1;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_Label_Distance;
extern lv_obj_t * ui_Label_Distance_Number;
extern lv_obj_t * ui_Label_km4;
extern lv_obj_t * ui_Group_Complete;
extern lv_obj_t * ui_Label_Complete;
extern lv_obj_t * ui_Label_Complete_Number;
extern lv_obj_t * ui_Label_Mins;
extern lv_obj_t * ui_Group_Battery_Indicator;
extern lv_obj_t * ui_Particle_Group;
extern lv_obj_t * ui_Image_Particle1;
extern lv_obj_t * ui_Wave_Group;
extern lv_obj_t * ui_Wave1;
extern lv_obj_t * ui_Image_Particle2;
extern lv_obj_t * ui_Wave2;
extern lv_obj_t * ui_Image_Particle3;
extern lv_obj_t * ui_Image_Battery_BG;
extern lv_obj_t * ui_Group_Pin;
extern lv_obj_t * ui_Group_Title2;
extern lv_obj_t * ui_Title_BG2;
extern lv_obj_t * ui_Label_Unlock;
extern lv_obj_t * ui_Group_Pin1;
void ui_event_Button_Pin1(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin1;
extern lv_obj_t * ui_Label_1;
extern lv_obj_t * ui_Pin_Add1;
void ui_event_Button_Pin2(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin2;
extern lv_obj_t * ui_Label_2;
extern lv_obj_t * ui_Pin_Add2;
void ui_event_Button_Pin3(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin3;
extern lv_obj_t * ui_Label_3;
extern lv_obj_t * ui_Pin_Add3;
void ui_event_Button_Pin4(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin4;
extern lv_obj_t * ui_Label_4;
extern lv_obj_t * ui_Pin_Add4;
void ui_event_Button_Pin5(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin5;
extern lv_obj_t * ui_Label_5;
extern lv_obj_t * ui_Pin_Add5;
void ui_event_Button_Pin6(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin6;
extern lv_obj_t * ui_Label_6;
extern lv_obj_t * ui_Pin_Add6;
void ui_event_Button_Pin7(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin7;
extern lv_obj_t * ui_Label_7;
extern lv_obj_t * ui_Pin_Add7;
void ui_event_Button_Pin8(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin8;
extern lv_obj_t * ui_Label_8;
extern lv_obj_t * ui_Pin_Add8;
void ui_event_Button_Pin9(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin9;
extern lv_obj_t * ui_Label_9;
extern lv_obj_t * ui_Pin_Add9;
void ui_event_Button_PinX(lv_event_t * e);
extern lv_obj_t * ui_Button_PinX;
extern lv_obj_t * ui_Pin_Add10;
extern lv_obj_t * ui_Image_X;
void ui_event_Button_Pin0(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin0;
extern lv_obj_t * ui_Label_0;
extern lv_obj_t * ui_Pin_Add11;
void ui_event_Button_PinOK(lv_event_t * e);
extern lv_obj_t * ui_Button_PinOK;
extern lv_obj_t * ui_Pin_Add12;
extern lv_obj_t * ui_Image_Ok;
extern lv_obj_t * ui_txtPin;
extern lv_obj_t * ui_Group_Info;
extern lv_obj_t * ui_Group_Title3;
extern lv_obj_t * ui_Title_BG3;
extern lv_obj_t * ui_Label_Unlock1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_lblHeatingStatus;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Speed_Number_2;
extern lv_obj_t * ui_Speed_Number_1;
extern lv_obj_t * ui_Menu;
void ui_event_BTN_Settings(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings;
extern lv_obj_t * ui_lblSETPOINT;
extern lv_obj_t * ui_lblDate;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_imgWiFi;
extern lv_obj_t * ui_imgOn;
extern lv_obj_t * ui_imgOff;
// SCREEN: ui_Settings_Wifi_Bus
void ui_Settings_Wifi_Bus_screen_init(void);
extern lv_obj_t * ui_Settings_Wifi_Bus;
extern lv_obj_t * ui_Group_Header1;
extern lv_obj_t * ui_Head_Group2;
extern lv_obj_t * ui_Chart_Group;
void ui_event_chkSoftstart1(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart1;
void ui_event_chkSoftstart2(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart2;
void ui_event_chkSoftstart3(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart3;
void ui_event_chkSoftstart4(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart4;
void ui_event_chkSoftstart5(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart5;
void ui_event_chkSoftstart6(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart6;
void ui_event_chkSoftstart7(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart7;
void ui_event_chkSoftstart8(lv_event_t * e);
extern lv_obj_t * ui_chkSoftstart8;
extern lv_obj_t * ui_dpdSoftstart1;
extern lv_obj_t * ui_dpdSoftstart2;
extern lv_obj_t * ui_dpdSoftstart3;
extern lv_obj_t * ui_dpdSoftstart4;
extern lv_obj_t * ui_dpdSoftstart5;
extern lv_obj_t * ui_dpdSoftstart6;
extern lv_obj_t * ui_dpdSoftstart7;
extern lv_obj_t * ui_dpdSoftstart8;
extern lv_obj_t * ui_lblRSBUSSETTINGS;
extern lv_obj_t * ui_lblThermostatSettings;
extern lv_obj_t * ui_Menu1;
void ui_event_BTN_Settings1(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings1;
extern lv_obj_t * ui_lblHysteresis;
extern lv_obj_t * ui_lblSensorOffset;
extern lv_obj_t * ui_lblDisplaySettings;
void ui_event_sldBacklightHigh(lv_event_t * e);
extern lv_obj_t * ui_sldBacklightHigh;
void ui_event_sldHysteresis(lv_event_t * e);
extern lv_obj_t * ui_sldHysteresis;
void ui_event_sldSensorOffset(lv_event_t * e);
extern lv_obj_t * ui_sldSensorOffset;
extern lv_obj_t * ui_lblBacklightHigh;
extern lv_obj_t * ui_valHysteresis;
extern lv_obj_t * ui_lblCelsious1;
extern lv_obj_t * ui_valSensorOffset;
extern lv_obj_t * ui_lblCelsious2;
extern lv_obj_t * ui_valOffsetWithTemperature;
extern lv_obj_t * ui_lblCelsious3;
extern lv_obj_t * ui_chkWifi;
extern lv_obj_t * ui_lblWiFiSettings;
extern lv_obj_t * ui_chkScreensaver;
extern lv_obj_t * ui_Dropdown1;
// SCREEN: ui_Screensaver
void ui_Screensaver_screen_init(void);
extern lv_obj_t * ui_Screensaver;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_ebike_bg_png);    // assets/ebike_bg.png
LV_IMG_DECLARE(ui_img_speed_slider_png);    // assets/speed_slider.png
LV_IMG_DECLARE(ui_img_slider_battery_png);    // assets/slider_battery.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets/menu_on.png
LV_IMG_DECLARE(ui_img_icn_lock_png);    // assets/icn_lock.png
LV_IMG_DECLARE(ui_img_icn_battery_png);    // assets/icn_battery.png
LV_IMG_DECLARE(ui_img_icn_map_png);    // assets/icn_map.png
LV_IMG_DECLARE(ui_img_menu_line_png);    // assets/menu_line.png
LV_IMG_DECLARE(ui_img_particle_1_png);    // assets/particle_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets/water_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets/particle_3.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets/water_1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets/particle_2.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets/battery_bg.png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets/pin_line.png
LV_IMG_DECLARE(ui_img_pin_on_png);    // assets/pin_on.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets/icn_x.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets/icn_ok.png
LV_IMG_DECLARE(ui_img_fire_png);    // assets/fire.png
LV_IMG_DECLARE(ui_img_settings_corner_png);    // assets/settings_corner.png
LV_IMG_DECLARE(ui_img_icn_settings_png);    // assets/icn_settings.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_icn_charge_png);    // assets/icn_charge.png
LV_IMG_DECLARE(ui_img_thoff_png);    // assets/thOff.png
LV_IMG_DECLARE(ui_img_settings_bg_png);    // assets/settings_bg.png
LV_IMG_DECLARE(ui_img_icn_x2_png);    // assets/icn_x2.png
LV_IMG_DECLARE(ui_img_ebike_s1_png);    // assets/ebike_s1.png
LV_IMG_DECLARE(ui_img_ebike_s2_png);    // assets/ebike_s2.png
LV_IMG_DECLARE(ui_img_ebike_s3_png);    // assets/ebike_s3.png
LV_IMG_DECLARE(ui_img_ebike_s4_png);    // assets/ebike_s4.png



LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Montserrat48);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
