// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: termostat_V1

#ifndef _TERMOSTAT_V1_UI_H
#define _TERMOSTAT_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../.pio/libdeps/esp32-4827S043C/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Particle1_Animation(lv_obj_t * TargetObject, int delay);
void Particle2_Animation(lv_obj_t * TargetObject, int delay);
void Particle3_Animation(lv_obj_t * TargetObject, int delay);
void Fash_Animation(lv_obj_t * TargetObject, int delay);
void Wave1_Animation(lv_obj_t * TargetObject, int delay);
void Wave2_Animation(lv_obj_t * TargetObject, int delay);
void Off_Animation(lv_obj_t * TargetObject, int delay);
void On_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_BG1;
extern lv_obj_t * ui_lblCESIOUS;
extern lv_obj_t * ui_lblDEGREE;
void ui_event_Slider_Speed(lv_event_t * e);
extern lv_obj_t * ui_Slider_Speed;
extern lv_obj_t * ui_Slider_Battery;
extern lv_obj_t * ui_Group_Battery_Percent;
extern lv_obj_t * ui_Label_Number1;
extern lv_obj_t * ui_Label_Number2;
extern lv_obj_t * ui_Label_Number3;
extern lv_obj_t * ui_Label_Number4;
extern lv_obj_t * ui_Label_Number5;
extern lv_obj_t * ui_Group_Header2;
extern lv_obj_t * ui_Head_Group1;
extern lv_obj_t * ui_Label_Time3;
extern lv_obj_t * ui_LabeL_PM2;
extern lv_obj_t * ui_Group_Footer;
extern lv_obj_t * ui_Button_Group;
extern lv_obj_t * ui_BTN_Driving;
void ui_event_BTN_BG1(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_BTN_Battery;
void ui_event_BTN_BG2(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG2;
extern lv_obj_t * ui_ICN_Battery;
extern lv_obj_t * ui_BTN_MAp;
void ui_event_BTN_BG3(lv_event_t * e);
extern lv_obj_t * ui_BTN_BG3;
extern lv_obj_t * ui_ICN_Map;
extern lv_obj_t * ui_Group_Battery;
extern lv_obj_t * ui_Group_Title1;
extern lv_obj_t * ui_Title_BG1;
extern lv_obj_t * ui_Label_Battery_Information;
extern lv_obj_t * ui_Group_Content1;
extern lv_obj_t * ui_Group_Charging;
extern lv_obj_t * ui_LabeL_Charging;
extern lv_obj_t * ui_Label_Charging_Number;
extern lv_obj_t * ui_Label_Percent1;
extern lv_obj_t * ui_Group_Distance;
extern lv_obj_t * ui_Label_Distance;
extern lv_obj_t * ui_Label_Distance_Number;
extern lv_obj_t * ui_Label_km4;
extern lv_obj_t * ui_Group_Complete;
extern lv_obj_t * ui_Label_Complete;
extern lv_obj_t * ui_Label_Complete_Number;
extern lv_obj_t * ui_Label_Mins;
extern lv_obj_t * ui_Group_Battery_Indicator;
extern lv_obj_t * ui_Particle_Group;
extern lv_obj_t * ui_Image_Particle1;
extern lv_obj_t * ui_Wave_Group;
extern lv_obj_t * ui_Wave1;
extern lv_obj_t * ui_Image_Particle2;
extern lv_obj_t * ui_Wave2;
extern lv_obj_t * ui_Image_Particle3;
extern lv_obj_t * ui_Image_Battery_BG;
extern lv_obj_t * ui_Group_Pin;
extern lv_obj_t * ui_Group_Title2;
extern lv_obj_t * ui_Title_BG2;
extern lv_obj_t * ui_Label_Unlock;
extern lv_obj_t * ui_Group_Pin1;
void ui_event_Button_Pin1(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin1;
extern lv_obj_t * ui_Label_1;
extern lv_obj_t * ui_Pin_Add1;
void ui_event_Button_Pin2(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin2;
extern lv_obj_t * ui_Label_2;
extern lv_obj_t * ui_Pin_Add2;
void ui_event_Button_Pin3(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin3;
extern lv_obj_t * ui_Label_3;
extern lv_obj_t * ui_Pin_Add3;
void ui_event_Button_Pin4(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin4;
extern lv_obj_t * ui_Label_4;
extern lv_obj_t * ui_Pin_Add4;
void ui_event_Button_Pin5(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin5;
extern lv_obj_t * ui_Label_5;
extern lv_obj_t * ui_Pin_Add5;
void ui_event_Button_Pin6(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin6;
extern lv_obj_t * ui_Label_6;
extern lv_obj_t * ui_Pin_Add6;
void ui_event_Button_Pin7(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin7;
extern lv_obj_t * ui_Label_7;
extern lv_obj_t * ui_Pin_Add7;
void ui_event_Button_Pin8(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin8;
extern lv_obj_t * ui_Label_8;
extern lv_obj_t * ui_Pin_Add8;
void ui_event_Button_Pin9(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin9;
extern lv_obj_t * ui_Label_9;
extern lv_obj_t * ui_Pin_Add9;
void ui_event_Button_PinX(lv_event_t * e);
extern lv_obj_t * ui_Button_PinX;
extern lv_obj_t * ui_Pin_Add10;
extern lv_obj_t * ui_Image_X;
void ui_event_Button_Pin0(lv_event_t * e);
extern lv_obj_t * ui_Button_Pin0;
extern lv_obj_t * ui_Label_0;
extern lv_obj_t * ui_Pin_Add11;
void ui_event_Button_PinOK(lv_event_t * e);
extern lv_obj_t * ui_Button_PinOK;
extern lv_obj_t * ui_Pin_Add12;
extern lv_obj_t * ui_Image_Ok;
extern lv_obj_t * ui_Group_Map;
extern lv_obj_t * ui_Group_Title3;
extern lv_obj_t * ui_Title_BG3;
extern lv_obj_t * ui_Label_Unlock1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_lblThermostatMode;
extern lv_obj_t * ui_lblShedule;
extern lv_obj_t * ui_lblHeatingStatus;
extern lv_obj_t * ui_Speed_Number_2;
extern lv_obj_t * ui_Speed_Number_1;
extern lv_obj_t * ui_Menu;
void ui_event_BTN_Settings(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings;
extern lv_obj_t * ui_lblSETPOINT;
extern lv_obj_t * ui_lblROOM;
extern lv_obj_t * ui_chkONOFF;
// SCREEN: ui_Settings_Wifi_Bus
void ui_Settings_Wifi_Bus_screen_init(void);
extern lv_obj_t * ui_Settings_Wifi_Bus;
extern lv_obj_t * ui_Group_Header1;
extern lv_obj_t * ui_Head_Group2;
extern lv_obj_t * ui_Label_Time2;
extern lv_obj_t * ui_LabeL_PM1;
extern lv_obj_t * ui_Chart_Group;
void ui_event_Checkbox1(lv_event_t * e);
extern lv_obj_t * ui_Checkbox1;
void ui_event_Checkbox2(lv_event_t * e);
extern lv_obj_t * ui_Checkbox2;
void ui_event_Checkbox3(lv_event_t * e);
extern lv_obj_t * ui_Checkbox3;
void ui_event_Checkbox4(lv_event_t * e);
extern lv_obj_t * ui_Checkbox4;
void ui_event_Checkbox5(lv_event_t * e);
extern lv_obj_t * ui_Checkbox5;
void ui_event_Checkbox6(lv_event_t * e);
extern lv_obj_t * ui_Checkbox6;
void ui_event_Checkbox7(lv_event_t * e);
extern lv_obj_t * ui_Checkbox7;
void ui_event_Checkbox8(lv_event_t * e);
extern lv_obj_t * ui_Checkbox8;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Dropdown6;
extern lv_obj_t * ui_Dropdown7;
extern lv_obj_t * ui_Dropdown8;
extern lv_obj_t * ui_lblRSBUSSETTINGS;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_lblCONNECTED;
void ui_event_Checkbox9(lv_event_t * e);
extern lv_obj_t * ui_Checkbox9;
extern lv_obj_t * ui_lblWIFISETTINGS;
void ui_event_btnCONNECT(lv_event_t * e);
extern lv_obj_t * ui_btnCONNECT;
extern lv_obj_t * ui_lblCONNECT;
extern lv_obj_t * ui_lblPASSWORD;
extern lv_obj_t * ui_lblNAME;
void ui_event_txtPASSWORD(lv_event_t * e);
extern lv_obj_t * ui_txtPASSWORD;
void ui_event_txtUSERNAME(lv_event_t * e);
extern lv_obj_t * ui_txtUSERNAME;
void ui_event_btnSEARCH(lv_event_t * e);
extern lv_obj_t * ui_btnSEARCH;
extern lv_obj_t * ui_lblSEARCH;
extern lv_obj_t * ui_dplWIFILIST;
extern lv_obj_t * ui_Menu1;
void ui_event_BTN_Settings1(lv_event_t * e);
extern lv_obj_t * ui_BTN_Settings1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown10;
extern lv_obj_t * ui_Label3;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_ebike_bg_png);    // assets/ebike_bg.png
LV_IMG_DECLARE(ui_img_speed_slider_png);    // assets/speed_slider.png
LV_IMG_DECLARE(ui_img_slider_battery_png);    // assets/slider_battery.png
LV_IMG_DECLARE(ui_img_menu_on_png);    // assets/menu_on.png
LV_IMG_DECLARE(ui_img_icn_lock_png);    // assets/icn_lock.png
LV_IMG_DECLARE(ui_img_icn_battery_png);    // assets/icn_battery.png
LV_IMG_DECLARE(ui_img_icn_map_png);    // assets/icn_map.png
LV_IMG_DECLARE(ui_img_menu_line_png);    // assets/menu_line.png
LV_IMG_DECLARE(ui_img_particle_1_png);    // assets/particle_1.png
LV_IMG_DECLARE(ui_img_water_2_png);    // assets/water_2.png
LV_IMG_DECLARE(ui_img_particle_3_png);    // assets/particle_3.png
LV_IMG_DECLARE(ui_img_water_1_png);    // assets/water_1.png
LV_IMG_DECLARE(ui_img_particle_2_png);    // assets/particle_2.png
LV_IMG_DECLARE(ui_img_battery_bg_png);    // assets/battery_bg.png
LV_IMG_DECLARE(ui_img_pin_line_png);    // assets/pin_line.png
LV_IMG_DECLARE(ui_img_pin_on_png);    // assets/pin_on.png
LV_IMG_DECLARE(ui_img_icn_x_png);    // assets/icn_x.png
LV_IMG_DECLARE(ui_img_icn_ok_png);    // assets/icn_ok.png
LV_IMG_DECLARE(ui_img_fire_png);    // assets/fire.png
LV_IMG_DECLARE(ui_img_settings_corner_png);    // assets/settings_corner.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_settings_bg_png);    // assets/settings_bg.png
LV_IMG_DECLARE(ui_img_icn_x2_png);    // assets/icn_x2.png
LV_IMG_DECLARE(ui_img_ebike_s1_png);    // assets/ebike_s1.png
LV_IMG_DECLARE(ui_img_ebike_s2_png);    // assets/ebike_s2.png
LV_IMG_DECLARE(ui_img_ebike_s3_png);    // assets/ebike_s3.png
LV_IMG_DECLARE(ui_img_ebike_s4_png);    // assets/ebike_s4.png



LV_FONT_DECLARE(ui_font_Big);
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Small);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
