// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: termostat_V1

#include "ui.h"
#include <stdio.h>
#include <esp32_smartdisplay.h>
extern float setpointTemp;
extern float offsetTemp;
extern float hysteresisTemp;
extern float roomTemp;
extern float ntcTemp;
extern bool printrd;
extern char printlog[];
bool value_changed = false;

void btnConnectClicked(lv_event_t * e)
{
	// Your code here
}

void btnSearchClicked(lv_event_t * e)
{
	// Your code here
}

void pin1click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '1');
}

void pin2click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '2');
}

void pin3click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '3');
}

void pin4click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '4');
}

void pin5click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '5');
}

void pin6click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '6');
}

void pin7click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '7');
}

void pin8click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '8');
}

void pin9click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '9');
}

void pinXclick(lv_event_t * e)
{
	lv_textarea_del_char(ui_txtPin);
}

void pin0click(lv_event_t * e)
{
	lv_textarea_add_char(ui_txtPin, '0');
}

void pinOKclick(lv_event_t * e)
{
	const char pass[] = {"1234"};
	const char* user = lv_textarea_get_text(ui_txtPin);
	if(strcmp(pass,user) == 0){
		lv_obj_clear_flag (ui_BTN_Settings, LV_OBJ_FLAG_HIDDEN);
	}else {
		lv_obj_add_flag (ui_BTN_Settings, LV_OBJ_FLAG_HIDDEN);
	}
}

void updateThermostatState(lv_event_t * e)
{
	// Your code here
}

void updateSettings(lv_event_t * e)
{
	// Your code here
}

void updateBacklightHigh(lv_event_t * e)
{
	int v = lv_slider_get_value(ui_sldBacklightHigh);
	smartdisplay_lcd_set_backlight(v/10.0);
}

void updateHysteresis(lv_event_t * e)
{
	char txt[16] = {0};
	int v = lv_slider_get_value(ui_sldHysteresis);
	lv_label_set_text_fmt(ui_valHysteresis,  "%d,%d", v / 10, v % 10);
	hysteresisTemp = v / 10.0;
	int n = sprintf(printlog, "Hysteresis %+0.1f", hysteresisTemp);
	printrd = true;
}

void updateSensorOffset(lv_event_t * e)
{
	char txt[16] = {0};
	int v = lv_slider_get_value(ui_sldSensorOffset);
	offsetTemp = v / 10.0;
	int n = sprintf(txt, "%+0.1f", ntcTemp + offsetTemp);
	lv_label_set_text_fmt(ui_valOffsetWithTemperature, txt);
	n = sprintf(txt, "%+0.1f", offsetTemp);
	lv_label_set_text_fmt(ui_valSensorOffset, txt);
	n = sprintf(printlog, "SensorOffset %+0.1f", offsetTemp);
	printrd = true;

}            


void initScreen(lv_event_t * e)
{
	// Your code here
}
