// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: termostat_V1

#include "ui.h"

void btnSearchClicked(lv_event_t * e)
{
	// Your code here
}

void btnConnectClicked(lv_event_t * e)
{
	// Your code here
}
