// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: termostat_V1

#include "../ui.h"

void ui_Settings_Wifi_Bus_screen_init(void)
{
    ui_Settings_Wifi_Bus = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings_Wifi_Bus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Wifi_Bus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Wifi_Bus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Settings_Wifi_Bus, &ui_img_settings_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Group_Header1 = lv_obj_create(ui_Settings_Wifi_Bus);
    lv_obj_set_height(ui_Group_Header1, 24);
    lv_obj_set_width(ui_Group_Header1, lv_pct(100));
    lv_obj_set_align(ui_Group_Header1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Group_Header1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Group_Header1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Group_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Group_Header1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Group_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Head_Group2 = lv_obj_create(ui_Group_Header1);
    lv_obj_set_height(ui_Head_Group2, lv_pct(110));
    lv_obj_set_flex_grow(ui_Head_Group2, 1);
    lv_obj_set_align(ui_Head_Group2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Head_Group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Head_Group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Head_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Head_Group2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Head_Group2, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Head_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Head_Group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_Group = lv_obj_create(ui_Settings_Wifi_Bus);
    lv_obj_set_height(ui_Chart_Group, 248);
    lv_obj_set_width(ui_Chart_Group, lv_pct(98));
    lv_obj_set_x(ui_Chart_Group, 0);
    lv_obj_set_y(ui_Chart_Group, 7);
    lv_obj_set_align(ui_Chart_Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Chart_Group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chart_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart_Group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkSoftstart1 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart1, " SOFTSTART1");
    lv_obj_set_width(ui_chkSoftstart1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart1, 85);
    lv_obj_set_y(ui_chkSoftstart1, -63);
    lv_obj_set_align(ui_chkSoftstart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart1, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart2 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart2, " SOFTSTART2");
    lv_obj_set_width(ui_chkSoftstart2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart2, 86);
    lv_obj_set_y(ui_chkSoftstart2, -40);
    lv_obj_set_align(ui_chkSoftstart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart3 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart3, " SOFTSTART3");
    lv_obj_set_width(ui_chkSoftstart3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart3, 86);
    lv_obj_set_y(ui_chkSoftstart3, -17);
    lv_obj_set_align(ui_chkSoftstart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart3, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart4 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart4, " SOFTSTART4");
    lv_obj_set_width(ui_chkSoftstart4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart4, 86);
    lv_obj_set_y(ui_chkSoftstart4, 7);
    lv_obj_set_align(ui_chkSoftstart4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart4, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart5 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart5, " SOFTSTART5");
    lv_obj_set_width(ui_chkSoftstart5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart5, 86);
    lv_obj_set_y(ui_chkSoftstart5, 31);
    lv_obj_set_align(ui_chkSoftstart5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart5, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart6 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart6, " SOFTSTART6");
    lv_obj_set_width(ui_chkSoftstart6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart6, 87);
    lv_obj_set_y(ui_chkSoftstart6, 55);
    lv_obj_set_align(ui_chkSoftstart6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart6, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart6, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart7 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart7, " SOFTSTART7");
    lv_obj_set_width(ui_chkSoftstart7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart7, 86);
    lv_obj_set_y(ui_chkSoftstart7, 79);
    lv_obj_set_align(ui_chkSoftstart7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart7, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart7, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_chkSoftstart8 = lv_checkbox_create(ui_Chart_Group);
    lv_checkbox_set_text(ui_chkSoftstart8, " SOFTSTART8");
    lv_obj_set_width(ui_chkSoftstart8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkSoftstart8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkSoftstart8, 87);
    lv_obj_set_y(ui_chkSoftstart8, 103);
    lv_obj_set_align(ui_chkSoftstart8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkSoftstart8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkSoftstart8, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkSoftstart8, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_dpdSoftstart1 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart1, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart1, 70);
    lv_obj_set_height(ui_dpdSoftstart1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart1, 185);
    lv_obj_set_y(ui_dpdSoftstart1, -64);
    lv_obj_set_align(ui_dpdSoftstart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart2 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart2, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart2, 70);
    lv_obj_set_height(ui_dpdSoftstart2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart2, 185);
    lv_obj_set_y(ui_dpdSoftstart2, -40);
    lv_obj_set_align(ui_dpdSoftstart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart3 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart3, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart3, 70);
    lv_obj_set_height(ui_dpdSoftstart3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart3, 185);
    lv_obj_set_y(ui_dpdSoftstart3, -16);
    lv_obj_set_align(ui_dpdSoftstart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart4 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart4, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart4, 70);
    lv_obj_set_height(ui_dpdSoftstart4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart4, 185);
    lv_obj_set_y(ui_dpdSoftstart4, 8);
    lv_obj_set_align(ui_dpdSoftstart4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart5 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart5, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart5, 70);
    lv_obj_set_height(ui_dpdSoftstart5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart5, 185);
    lv_obj_set_y(ui_dpdSoftstart5, 32);
    lv_obj_set_align(ui_dpdSoftstart5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart6 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart6, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart6, 70);
    lv_obj_set_height(ui_dpdSoftstart6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart6, 185);
    lv_obj_set_y(ui_dpdSoftstart6, 56);
    lv_obj_set_align(ui_dpdSoftstart6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart7 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart7, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart7, 70);
    lv_obj_set_height(ui_dpdSoftstart7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart7, 185);
    lv_obj_set_y(ui_dpdSoftstart7, 80);
    lv_obj_set_align(ui_dpdSoftstart7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_dpdSoftstart8 = lv_dropdown_create(ui_Chart_Group);
    lv_dropdown_set_options(ui_dpdSoftstart8, "12VAC\n16VAC\n24VAC\n36VAC");
    lv_obj_set_width(ui_dpdSoftstart8, 70);
    lv_obj_set_height(ui_dpdSoftstart8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dpdSoftstart8, 185);
    lv_obj_set_y(ui_dpdSoftstart8, 104);
    lv_obj_set_align(ui_dpdSoftstart8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dpdSoftstart8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_lblRSBUSSETTINGS = lv_label_create(ui_Chart_Group);
    lv_obj_set_width(ui_lblRSBUSSETTINGS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRSBUSSETTINGS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRSBUSSETTINGS, -28);
    lv_obj_set_y(ui_lblRSBUSSETTINGS, 22);
    lv_obj_set_align(ui_lblRSBUSSETTINGS, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblRSBUSSETTINGS, "RS485 Bus Settings");
    lv_obj_set_style_text_color(ui_lblRSBUSSETTINGS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRSBUSSETTINGS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRSBUSSETTINGS, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblThermostatSettings = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblThermostatSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblThermostatSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblThermostatSettings, -277);
    lv_obj_set_y(ui_lblThermostatSettings, 39);
    lv_obj_set_align(ui_lblThermostatSettings, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblThermostatSettings, "Thermostat Settings");
    lv_obj_set_style_text_color(ui_lblThermostatSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblThermostatSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblThermostatSettings, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu1 = lv_img_create(ui_Settings_Wifi_Bus);
    lv_img_set_src(ui_Menu1, &ui_img_settings_corner_png);
    lv_obj_set_width(ui_Menu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Menu1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Menu1, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_Menu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Settings1 = lv_btn_create(ui_Menu1);
    lv_obj_set_width(ui_BTN_Settings1, 35);
    lv_obj_set_height(ui_BTN_Settings1, 30);
    lv_obj_set_align(ui_BTN_Settings1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BTN_Settings1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN_Settings1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTN_Settings1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Settings1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTN_Settings1, &ui_img_icn_x2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHysteresis = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblHysteresis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHysteresis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHysteresis, -183);
    lv_obj_set_y(ui_lblHysteresis, -69);
    lv_obj_set_align(ui_lblHysteresis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHysteresis, "Hysteresis");

    ui_lblSensorOffset = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblSensorOffset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSensorOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSensorOffset, -171);
    lv_obj_set_y(ui_lblSensorOffset, -36);
    lv_obj_set_align(ui_lblSensorOffset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSensorOffset, "Sensor Offset");

    ui_lblDisplaySettings = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblDisplaySettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDisplaySettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDisplaySettings, -313);
    lv_obj_set_y(ui_lblDisplaySettings, 137);
    lv_obj_set_align(ui_lblDisplaySettings, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblDisplaySettings, "Display Settings");
    lv_obj_set_style_text_color(ui_lblDisplaySettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDisplaySettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDisplaySettings, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldBacklightHigh = lv_slider_create(ui_Settings_Wifi_Bus);
    lv_slider_set_range(ui_sldBacklightHigh, 1, 10);
    lv_slider_set_value(ui_sldBacklightHigh, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldBacklightHigh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldBacklightHigh, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_sldBacklightHigh, 102);
    lv_obj_set_height(ui_sldBacklightHigh, 10);
    lv_obj_set_x(ui_sldBacklightHigh, -167);
    lv_obj_set_y(ui_sldBacklightHigh, 54);
    lv_obj_set_align(ui_sldBacklightHigh, LV_ALIGN_CENTER);


    ui_sldHysteresis = lv_slider_create(ui_Settings_Wifi_Bus);
    lv_slider_set_range(ui_sldHysteresis, 0, 50);
    lv_slider_set_value(ui_sldHysteresis, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldHysteresis) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldHysteresis, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_sldHysteresis, 150);
    lv_obj_set_height(ui_sldHysteresis, 10);
    lv_obj_set_x(ui_sldHysteresis, -144);
    lv_obj_set_y(ui_sldHysteresis, -52);
    lv_obj_set_align(ui_sldHysteresis, LV_ALIGN_CENTER);


    ui_sldSensorOffset = lv_slider_create(ui_Settings_Wifi_Bus);
    lv_slider_set_range(ui_sldSensorOffset, -100, 100);
    lv_slider_set_value(ui_sldSensorOffset, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldSensorOffset) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldSensorOffset, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_sldSensorOffset, 150);
    lv_obj_set_height(ui_sldSensorOffset, 10);
    lv_obj_set_x(ui_sldSensorOffset, -144);
    lv_obj_set_y(ui_sldSensorOffset, -20);
    lv_obj_set_align(ui_sldSensorOffset, LV_ALIGN_CENTER);


    ui_lblBacklightHigh = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblBacklightHigh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBacklightHigh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBacklightHigh, -167);
    lv_obj_set_y(ui_lblBacklightHigh, 34);
    lv_obj_set_align(ui_lblBacklightHigh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBacklightHigh, "Backlight High");

    ui_valHysteresis = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_valHysteresis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valHysteresis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valHysteresis, -33);
    lv_obj_set_y(ui_valHysteresis, -52);
    lv_obj_set_align(ui_valHysteresis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valHysteresis, "50");

    ui_lblCelsious1 = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblCelsious1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCelsious1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCelsious1, -14);
    lv_obj_set_y(ui_lblCelsious1, -52);
    lv_obj_set_align(ui_lblCelsious1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCelsious1, "°C");

    ui_valSensorOffset = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_valSensorOffset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valSensorOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valSensorOffset, -45);
    lv_obj_set_y(ui_valSensorOffset, -21);
    lv_obj_set_align(ui_valSensorOffset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valSensorOffset, "50");

    ui_lblCelsious2 = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblCelsious2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCelsious2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCelsious2, -15);
    lv_obj_set_y(ui_lblCelsious2, -20);
    lv_obj_set_align(ui_lblCelsious2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCelsious2, "°C");

    ui_valOffsetWithTemperature = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_valOffsetWithTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valOffsetWithTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valOffsetWithTemperature, -45);
    lv_obj_set_y(ui_valOffsetWithTemperature, -2);
    lv_obj_set_align(ui_valOffsetWithTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_valOffsetWithTemperature, "50");

    ui_lblCelsious3 = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblCelsious3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCelsious3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCelsious3, -15);
    lv_obj_set_y(ui_lblCelsious3, -1);
    lv_obj_set_align(ui_lblCelsious3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCelsious3, "°C");

    ui_chkWifi = lv_checkbox_create(ui_Settings_Wifi_Bus);
    lv_checkbox_set_text(ui_chkWifi, " WiFi enable");
    lv_obj_set_width(ui_chkWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkWifi, -165);
    lv_obj_set_y(ui_chkWifi, 106);
    lv_obj_set_align(ui_chkWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_chkWifi, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_chkWifi, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_lblWiFiSettings = lv_label_create(ui_Settings_Wifi_Bus);
    lv_obj_set_width(ui_lblWiFiSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWiFiSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWiFiSettings, -340);
    lv_obj_set_y(ui_lblWiFiSettings, 205);
    lv_obj_set_align(ui_lblWiFiSettings, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblWiFiSettings, "WIFI Settings");
    lv_obj_set_style_text_color(ui_lblWiFiSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWiFiSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWiFiSettings, &ui_font_Big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chkScreensaver = lv_checkbox_create(ui_Settings_Wifi_Bus);
    lv_checkbox_set_text(ui_chkScreensaver, " Screensaver");
    lv_obj_set_width(ui_chkScreensaver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chkScreensaver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chkScreensaver, -41);
    lv_obj_set_y(ui_chkScreensaver, 51);
    lv_obj_set_align(ui_chkScreensaver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chkScreensaver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Settings_Wifi_Bus);
    lv_dropdown_set_options(ui_Dropdown1,
                            "GMT+14:00\n	GMT+13:00\n	GMT+12:00\n	GMT+11:00\n	GMT+10:00\n	GMT+9:00\n	GMT+8:00\n	GMT+7:00\n	GMT+6:00\n	GMT+5:00\n	GMT+4:00\n	GMT+3:00\n	GMT+2:00\n	GMT+1:00\n	GMT+0:00\n	GMT-1:00\n	GMT-2:00\n	GMT-3:00\n	GMT-4:00\n	GMT-5:00\n	GMT-6:00\n	GMT-7:00\n	GMT-8:00\n	GMT-9:00\n	GMT-10:00\n	GMT-11:00\n	GMT-12:00");
    lv_obj_set_width(ui_Dropdown1, 96);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -51);
    lv_obj_set_y(ui_Dropdown1, 105);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_chkSoftstart1, ui_event_chkSoftstart1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart2, ui_event_chkSoftstart2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart3, ui_event_chkSoftstart3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart4, ui_event_chkSoftstart4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart5, ui_event_chkSoftstart5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart6, ui_event_chkSoftstart6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart7, ui_event_chkSoftstart7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chkSoftstart8, ui_event_chkSoftstart8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Settings1, ui_event_BTN_Settings1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldBacklightHigh, ui_event_sldBacklightHigh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldHysteresis, ui_event_sldHysteresis, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldSensorOffset, ui_event_sldSensorOffset, LV_EVENT_ALL, NULL);

}
